version: '3.8'

services:
  notification-service:
    build: .
    container_name: notification-service
    ports:
      - "8085:4567"
    environment:
      - SMTP_ADDRESS=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=revelobladimir2@gmail.com
      - SMTP_PASSWORD=indx neko pkcn tgpj
    restart: always